// Decide what to do to the pull request's review comments, from data alone:
// the changed Markdown files with their head content and patch, and the
// review comments already on the pull request. Pure, so every rule below is
// tested without GitHub. `run.ts` fetches the inputs and applies the output.
import { anchorRange, changedWithin, parsePatch } from './diff';
import { type PreviewLinks, previewLinks } from './encode';
import { findMermaidBlocks } from './markdown';

export type FileStatus =
  | 'added'
  | 'removed'
  | 'modified'
  | 'renamed'
  | 'copied'
  | 'changed'
  | 'unchanged';

export interface ChangedFile {
  path: string;
  status: FileStatus;
  /** Added plus deleted lines; 0 for a pure rename. */
  changes: number;
  /** Unified diff for the file; absent when GitHub omits it (too large, or a pure rename). */
  patch?: string | undefined;
  /** Head content; absent for a removed, non-Markdown or unreadable file. */
  content?: string | undefined;
  /** Why the head content could not be read, when `content` is absent for that reason. */
  unreadable?: string | undefined;
}

export interface ExistingComment {
  id: number;
  path: string;
  body: string;
  /** The last (or only) line of the comment's range; null once GitHub marks it outdated. */
  line: number | null;
  /** The first line of a multi-line comment; null for a single-line one. */
  startLine: number | null;
}

export interface DesiredComment {
  key: string;
  path: string;
  startLine: number;
  line: number;
  body: string;
  /** The mermaid.live editor URL, for a venue with no comment body (the job summary). */
  link: string;
}

export interface Plan {
  create: DesiredComment[];
  update: (DesiredComment & { id: number })[];
  remove: { id: number; key: string }[];
  /** Files skipped and why, for the job summary. */
  skipped: { path: string; reason: string }[];
}

const MARKER_PREFIX = '<!-- mermaid-preview:';

export const COMMENT_TYPES = ['image', 'link'] as const;
export type CommentType = (typeof COMMENT_TYPES)[number];

export function isCommentType(value: string): value is CommentType {
  return (COMMENT_TYPES as readonly string[]).includes(value);
}

export interface BodyOptions {
  theme: string;
  /** `image`: the rendered diagram, itself the link. `link`: a text link. */
  type: CommentType;
  /** Append the "Generated by" footer. */
  attribution: boolean;
}

const FOOTER =
  '<sub>Generated by <a href="https://github.com/marketplace/actions/mermaid-preview">bje-actions/mermaid-preview</a></sub>';

/** The identity a comment keeps across pushes: file path and block ordinal. */
export function commentKey(path: string, ordinal: number): string {
  return `${path}#${ordinal}`;
}

export function marker(key: string): string {
  return `${MARKER_PREFIX} ${key} -->`;
}

export function keyOf(body: string): string | null {
  const match = /^<!-- mermaid-preview: (.+?) -->/m.exec(body);
  return match === null ? null : (match[1] as string);
}

/** `links` are `code`'s on the `theme` input, which `plan` also keeps as the comment's `link`. */
export function buildBody(
  key: string,
  code: string,
  links: PreviewLinks,
  options: BodyOptions,
): string {
  const lines = [
    marker(key),
    // The view URL rides along hidden, for tooling that reads the raw body
    // (GitHub strips HTML comments from the rendered page).
    `<!-- mermaid-preview-view: ${links.view} -->`,
    // One visible link either way, to the editor. The text form is worded so
    // nobody expects to edit the pull request from there.
    options.type === 'image' ? picture(code, links) : `[View in mermaid.live](${links.edit})`,
  ];
  if (options.attribution) lines.push('', FOOTER);
  return lines.join('\n');
}

// GitHub's own page backgrounds for each appearance, as mermaid.ink's bgColor,
// so the render sits flush with the comment rather than in a box.
const LIGHT_BACKGROUND = 'ffffff';
const DARK_BACKGROUND = '0d1117';

/**
 * A theme-aware image linked to the editor. GitHub keeps a `<picture>` with a
 * `prefers-color-scheme: dark` source in comments (probed on PR #10), so dark
 * mode readers get a render on Mermaid's dark theme, light mode readers the
 * `theme` input's render.
 */
function picture(code: string, links: PreviewLinks): string {
  const dark = `${previewLinks(code, 'dark').image}?bgColor=${DARK_BACKGROUND}`;
  const light = `${links.image}?bgColor=${LIGHT_BACKGROUND}`;
  return (
    `<a href="${links.edit}"><picture>` +
    `<source media="(prefers-color-scheme: dark)" srcset="${dark}">` +
    `<img alt="Mermaid diagram, opens in mermaid.live" src="${light}">` +
    '</picture></a>'
  );
}

export function isMarkdown(path: string): boolean {
  return /\.(md|markdown|mdx)$/i.test(path);
}

export function plan(
  files: ChangedFile[],
  existing: ExistingComment[],
  options: BodyOptions,
): Plan {
  const desired = new Map<string, DesiredComment>();
  const skipped: Plan['skipped'] = [];

  for (const file of files) {
    if (!isMarkdown(file.path) || file.status === 'removed') continue;
    // A pure rename has no patch and no changed block; nothing to say.
    if (file.status === 'renamed' && file.changes === 0) continue;
    if (file.patch === undefined) {
      skipped.push({
        path: file.path,
        reason: 'GitHub returned no diff for this file (too large); open it on GitHub instead',
      });
      continue;
    }
    if (file.content === undefined) {
      skipped.push({ path: file.path, reason: file.unreadable ?? 'head content was not read' });
      continue;
    }
    const diff = parsePatch(file.patch);
    for (const block of findMermaidBlocks(file.content)) {
      const range = { start: block.startLine, end: block.endLine };
      if (!changedWithin(range, diff)) continue;
      const anchor = anchorRange(range, diff);
      // `parsePatch` keeps `added` and `deletedBefore` subsets of `inDiff`, so
      // a changed range always has an in-diff line and the anchor exists.
      /* v8 ignore next */
      if (anchor === null)
        throw new Error(`no anchor for a changed block at ${file.path}:${range.start}`);
      const key = commentKey(file.path, block.ordinal);
      const links = previewLinks(block.code, options.theme);
      desired.set(key, {
        key,
        path: file.path,
        startLine: anchor.start,
        line: anchor.end,
        body: buildBody(key, block.code, links, options),
        link: links.edit,
      });
    }
  }

  const result: Plan = { create: [], update: [], remove: [], skipped };
  const seen = new Set<string>();
  for (const comment of existing) {
    const key = keyOf(comment.body);
    if (key === null) continue;
    const want = desired.get(key);
    // A duplicate marker (two comments for one key) keeps the first and
    // removes the rest, so a partially applied earlier run self-heals.
    if (want === undefined || seen.has(key)) {
      result.remove.push({ id: comment.id, key });
      continue;
    }
    seen.add(key);
    // An outdated comment has `line: null`, so it never matches and is
    // replaced, which is what an outdated anchor needs.
    const startLine = comment.startLine ?? comment.line;
    const sameRange = startLine === want.startLine && comment.line === want.line;
    if (sameRange) {
      if (comment.body !== want.body) result.update.push({ ...want, id: comment.id });
    } else {
      // The API cannot move a comment's range: replace it.
      result.remove.push({ id: comment.id, key });
      result.create.push(want);
    }
  }
  for (const [key, want] of desired) {
    if (!seen.has(key)) result.create.push(want);
  }
  return result;
}
